In [380]:
import numpy as np
from numpy.random import randint, choice

In [98]:
population_size = 10
chromosome_length = 20
# Generate random values between 0 and 1. Generate 10 x 20 values
initial_uniform_values = np.random.uniform(0, 1, (population_size, chromosome_length))
initial_binary_population_boolean = initial_uniform_values >= 0.5
initial_binary_population = initial_binary_population_boolean.astype(int)

In [99]:
def bin_to_dec(bin_list):
    """
    bin_to_dec(bin_list)
    function that takes in a 2D list of binary values and converts 
    each list to decimal (base 2 format). The function treats each 
    item in the list as if they were a continuous binary number by 
    joining them together and does the conversion to decimal format
    bin_list: the 2D list
    Returns: a list of the converted base 2 numbers
    """
    #empty list that will contain the phenotyoes(base 2 values of the binary numbers)
    phenotypes = []

    # iteratively loop through the list and stringify the binary values then convert to base 2 int
    for i in bin_list:
        bin_str = ''
        for j in i:
            bin_str += str(j)
        phenotypes.append(int(bin_str, 2))

    return phenotypes

In [100]:
def solar_energy_fitness_calc(bin_list, min, max):
    """
    solar_energy_fitness_calc(bin_list, min, max)
    function that calculates the fitness values of each binary 
    number being evaluated in the genetic algorithm. The binary 
    number list is passed in as a 2D array whose values are lists 
    of binary values. The function treats each item in the list 
    as if they were a continuous binary number by joining them 
    together and does the conversion to decimal format before 
    calculating the fitness value
    bin_list: the 2D list
    min: the lower bound of the solar energy test problem
    max: the upper bound of the solar energy test problem
    Returns: a list of the fitness values of the binary values
    """
    # empty list that will store the fitness values of the binary values
    fitness_vals = []

    # iteratively convert the binary values to base 2 which you pass to the fitness function
    for index, i in enumerate(bin_to_dec(bin_list)):
        fitness_vals.append(min + (((max - min) * i) / 2**len(bin_list[index]) - 1))

    return fitness_vals

In [101]:
solar_energy_fitness_calc(initial_binary_population, 40, 90)

[74.6144905090332,
 44.94773292541504,
 55.884517669677734,
 86.62296676635742,
 69.74417114257812,
 42.12342643737793,
 47.85496139526367,
 75.54718399047852,
 72.34236145019531,
 62.75187873840332]

In [292]:
def crossover(bin_parents_list, type='single-point'):
    """
    crossover(bin_parents_list, type='single-point')
    function that performs a crossover of 2 parents in the population
    and returns 2 children
    The type of crossover is dependent on the argument passed in as an
    argument. Crossover is done by breaking down the chromosome at randomly
    selected points and concatenating with the other parents genes from that
    position. This is done without changing the genes of the parents since new
    children chromosomes are created
    bin_parents_list: a list of 2 parents that need a crossover done on them
    type(optional): the type of crossover desired to be done. The default type 
    is single point
    returns: a list of 2 children that result from the crossover
    """
    bin_children_list = []

    if type == 'single-point':
        # if the type is set to single-point, perform a single-point crossover
        crossover_point = randint(1, len(bin_parents_list[0])-1)
        '''
        slice the list from beginning to randomly selected index,
        append slice of second list from that point to the end to the first.
        perform the inverse on the second parent
        '''
        bin_children_list.append([*bin_parents_list[0][:crossover_point],\
                                  *bin_parents_list[1][crossover_point:]])
        bin_children_list.append([*bin_parents_list[1][:crossover_point],\
                                  *bin_parents_list[0][crossover_point:]])
    elif type == 'two-point':
        # if the type is set to two-point, perform a two-point crossover
        crossover_point = randint(low=1, high=len(bin_parents_list[0])-1, size=2)
        '''
        slice the list from beginning to the first randomly selected index, insert 
        part of the second part from that index up until the second randomly selected 
        index and add the last part of the forst index from that point to the end
        perform the inverse on the second parent
        '''
        bin_children_list.append([*bin_parents_list[0][:crossover_point[0]],\
                                  *bin_parents_list[1][crossover_point[0]:crossover_point[1]],\
                                  *bin_parents_list[0][crossover_point[1]:]])
        bin_children_list.append([*bin_parents_list[1][:crossover_point[0]],\
                                  *bin_parents_list[0][crossover_point[0]:crossover_point[1]],\
                                  *bin_parents_list[1][crossover_point[1]:]])
    elif type == 'uniform':
        # if the type is set to uniform, perform uniform crossover
        child1 = []
        child2 = []
        # randomly and uniformly swap bits between the two parents
        for i in range(len(bin_parents_list[0])):
            crossover_point = randint(0, 2)
            if crossover_point == 1:
                child1.append(bin_parents_list[1][i])
                child2.append(bin_parents_list[0][i])
            else:
                child1.append(bin_parents_list[0][i])
                child2.append(bin_parents_list[1][i])
        bin_children_list.append(child1)
        bin_children_list.append(child2)
                
    return np.array(bin_children_list)

In [248]:
print(initial_binary_population[0:2])
print(crossover(initial_binary_population[0:2]))

[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1]]
[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 0 1]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0]]


In [250]:
print(initial_binary_population[0:2])
print(crossover(initial_binary_population[0:2], type='two-point'))

[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1]]
[[1 0 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1]]


In [294]:
print(initial_binary_population[0:2])
print(crossover(initial_binary_population[0:2], type='uniform'))

[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1]]
[[1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 0 1 1]
 [0 0 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0]]


In [436]:
def mutate(bin_list, mutation_rate=0.1, mutation_ratio=0.1):
    """
    mutate(bin_list, mutation_rate=0.1, mutation_ratio=0.1)
    function that performs mutation of random individuals in
    a binary population. The number of individuals on which mutation
    will take place and the number of bits in an individual affected by
    the mutation are determined by the mutation rate and mutation ratio
    respectively
    bin_list: the binary population on in which mutation will is performed
    mutation_rate(optional): The percentage of the populations being mutated
    mutation_ratio(optional): The percentage of bits in the population being mutated
    returns: the population that has been mutated based in the parameters provided
    """
    '''
    randomly obtain the indices of the individuals being mutated. 
    The number of indices will approximately be based on the percentage 
    provided as the mutation_rate parameter
    '''
    mutation_chromosome_indices = choice(np.array(range(len(bin_list))),\
                                         int(len(bin_list) * mutation_rate),\
                                         replace=False)
    print("Mutation Chromosome indices:"+str(mutation_chromosome_indices))
    # loop through each individual in the population
    for i in mutation_chromosome_indices:
        '''
        randomly obtain the indices of the bits being mutated. 
        The number of indices will approximately be based on the percentage 
        provided as the mutation_ratio parameter
        '''
        mutation_gene_indices = choice(np.array(range(len(bin_list[i]))),\
                                         int(len(bin_list[i]) * mutation_ratio),\
                                         replace=False)
        # flip the bit
        for j in mutation_gene_indices:
            bin_list[i][j] = abs(bin_list[i][j] - 1)
        
    return np.array(bin_list)

In [438]:
print("Population before mutation:\n"+str(initial_binary_population))
print("------------------------------------------")
print("Population after mutation:\n"+str(mutate(initial_binary_population)))

Population before mutation:
[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 0 1 0 0]
 [0 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1]
 [1 0 0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0]
 [0 1 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0]
 [0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1]]
------------------------------------------
Mutation Chromosome indices:[1]
Population after mutation:
[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0]
 [0 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1]
 [1 0 0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0]
 [0 1 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0]
 [0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1]]


0