In [120]:
import numpy as np
from random import randint

In [98]:
population_size = 10
chromosome_length = 20
# Generate random values between 0 and 1. Generate 10 x 20 values
initial_uniform_values = np.random.uniform(0, 1, (population_size, chromosome_length))
initial_binary_population_boolean = initial_uniform_values >= 0.5
initial_binary_population = initial_binary_population_boolean.astype(int)

In [99]:
def bin_to_dec(bin_list):
    """
    bin_to_dec(bin_list): function that takes in a 2D list of 
    binary values and converts each list to decimal (base 2 format)
    The function treats each item in the list as if they were a 
    continuous binary number by joining them together and does the 
    conversion to decimal format
    bin_list: the 2D list
    Returns: a list of the converted base 2 numbers
    """
    #empty list that will contain the phenotyoes(base 2 values of the binary numbers)
    phenotypes = []

    # iteratively loop through the list and stringify the binary values then convert to base 2 int
    for i in bin_list:
        bin_str = ''
        for j in i:
            bin_str += str(j)
        phenotypes.append(int(bin_str, 2))

    return phenotypes

In [100]:
def solar_energy_fitness_calc(bin_list, min, max):
    """
    solar_energy_fitness_calc(bin_list, min, max): function that  
    calculates the fitness values of each binary number being 
    evaluated in the genetic algorithm. The binary number list 
    is passed in as a 2D array whose values are lists of binary values
    The function treats each item in the list as if they were a 
    continuous binary number by joining them together and does the 
    conversion to decimal format before calculating the fitness value
    bin_list: the 2D list
    min: the lower bound of the solar energy test problem
    max: the upper bound of the solar energy test problem
    Returns: a list of the fitness values of the binary values
    """
    # empty list that will store the fitness values of the binary values
    fitness_vals = []

    # iteratively convert the binary values to base 2 which you pass to the fitness function
    for index, i in enumerate(bin_to_dec(bin_list)):
        fitness_vals.append(min + (((max - min) * i) / 2**len(bin_list[index]) - 1))

    return fitness_vals

In [101]:
solar_energy_fitness_calc(initial_binary_population, 40, 90)

[74.6144905090332,
 44.94773292541504,
 55.884517669677734,
 86.62296676635742,
 69.74417114257812,
 42.12342643737793,
 47.85496139526367,
 75.54718399047852,
 72.34236145019531,
 62.75187873840332]

In [180]:
def crossover(bin_parents_list, type='single-point'):
    bin_children_list = []
    
    if type == 'single-point':
        crossover_point = randint(1, len(bin_parents_list[0])-2)
        bin_children_list.append([*bin_parents_list[0][:crossover_point], *bin_parents_list[1][crossover_point:]])
        bin_children_list.append([*bin_parents_list[1][:crossover_point], *bin_parents_list[0][crossover_point:]])

    return np.array(bin_children_list)

In [182]:
print(initial_binary_population[0:2])
print(crossover(initial_binary_population[0:2]))

[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1]]
[[1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1]
 [0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 0]]
