In [1756]:
import numpy as np
import math
from numpy.random import randint, choice

In [1757]:
                        #  x       y   Fitness f(x,y)
initial_population = [[6.7874, 6.9483, 13.5468],
                       [7.5774, 3.1710, -6.5969],
                       [7.4313, 9.5022, -5.7656],
                       [3.9223, 0.3445, 0.3149],
                       [6.5548, 4.3874, 8.7209],
                       [1.7119, 3.8156, 5.0089],
                       [7.0605, 7.6552, 3.4901],
                       [0.3183, 7.9520, -1.3994],
                       [2.7692, 1.8687, -3.9137],
                       [0.4617, 4.8976, -1.5065],
                       [0.9713, 4.4559, 1.7482],
                       [8.2346, 6.4631, 10.7287]]

In [1758]:
def get_rank_weighting(population, selection_rate):
    n_keep = math.ceil(selection_rate * len(population))
    sorted_population = sorted(population,key=lambda rank:rank[2], reverse=False)[:n_keep]
    survivers = []
    rank_sum = 0
    for i in range(n_keep):
        rank_sum += i + 1
    for idx, i in enumerate(sorted_population):
        rank = idx + 1
        survivers.append(list([rank]))
        for j in i:
            survivers[idx].append(j)
        probability = round((n_keep  - rank + 1) / rank_sum, 4)
        survivers[idx].append(probability)

    return survivers

In [1759]:
ranked_values = get_rank_weighting(initial_population, 0.5)
ranked_values

[[1, 7.5774, 3.171, -6.5969, 0.2857],
 [2, 7.4313, 9.5022, -5.7656, 0.2381],
 [3, 2.7692, 1.8687, -3.9137, 0.1905],
 [4, 0.4617, 4.8976, -1.5065, 0.1429],
 [5, 0.3183, 7.952, -1.3994, 0.0952],
 [6, 3.9223, 0.3445, 0.3149, 0.0476]]

 ## The above values are based on assumptions
 I think so because the values provided are out of the range provided in the Rastigrin's function

In [1761]:
def intitialize_population(lower_bound, upper_bound, var_count, pop_size=10):
    return np.random.uniform(lower_bound, upper_bound, (pop_size, var_count))

In [1762]:
population = intitialize_population(-5.12, 5.12, 2)
population

array([[ 0.26135283,  3.48163738],
       [-1.71142746,  2.77225633],
       [ 2.66025897, -4.21416235],
       [ 4.54527098,  3.23650939],
       [ 1.42833084,  1.98221383],
       [ 4.79237929, -3.12368315],
       [-5.16202485,  0.39550203],
       [ 2.75423992, -4.36420153],
       [ 1.9692937 ,  2.24593731],
       [ 0.10009278,  1.5990956 ]])

In [1763]:
def rastrigin_cost_func(population):
    population_cost = []
    for i in range(len(population)):
        population_cost.append(list([]))
        population_cost[i] = np.append(population_cost[i], round(population[i][0], 4))
        population_cost[i] = np.append(population_cost[i], round(population[i][1], 4))
        population_cost[i] = np.append(population_cost[i], round(20 + (population[i][0] ** 2 - \
                                                         (10 * math.cos(2 * math.pi * population[i][0]))) + \
                                                         (population[i][1] ** 2 - (10 * math.cos(2 * math.pi * population[i][1]))), 4))
    print("*----------------------------Performance------------------------------*")
    print("    Chromosomes           Scores")
    for i in population_cost:
        print("["+str(i[0])+", "+str(i[1])+"] ------> "+str(i[2]))
    print("*---------------------------------------------------------------------*")
    return population_cost

In [1764]:
population_cost = rastrigin_cost_func(population)
population_cost

*----------------------------Performance------------------------------*
    Chromosomes           Scores
[0.2614, 3.4816] ------> 42.8363
[-1.7114, 2.7723] ------> 31.6205
[2.6603, -4.2142] ------> 47.9479
[4.5453, 3.2365] ------> 59.886
[1.4283, 1.9822] ------> 25.0348
[4.7924, -3.1237] ------> 42.9636
[-5.162, 0.3955] ------> 49.4733
[2.7542, -4.3642] ------> 52.9411
[1.9693, 2.2459] ------> 18.8527
[0.1001, 1.5991] ------> 22.6038
*---------------------------------------------------------------------*


[array([ 0.2614,  3.4816, 42.8363]),
 array([-1.7114,  2.7723, 31.6205]),
 array([ 2.6603, -4.2142, 47.9479]),
 array([ 4.5453,  3.2365, 59.886 ]),
 array([ 1.4283,  1.9822, 25.0348]),
 array([ 4.7924, -3.1237, 42.9636]),
 array([-5.162 ,  0.3955, 49.4733]),
 array([ 2.7542, -4.3642, 52.9411]),
 array([ 1.9693,  2.2459, 18.8527]),
 array([ 0.1001,  1.5991, 22.6038])]

In [1765]:
ranked_values = get_rank_weighting(population_cost, 0.5)
ranked_values

[[1, 1.9693, 2.2459, 18.8527, 0.3333],
 [2, 0.1001, 1.5991, 22.6038, 0.2667],
 [3, 1.4283, 1.9822, 25.0348, 0.2],
 [4, -1.7114, 2.7723, 31.6205, 0.1333],
 [5, 0.2614, 3.4816, 42.8363, 0.0667]]

In [1766]:
selection_winners = []

for i in ranked_values:
    selection_winners.append(i[1:-2])

selection_winners

[[1.9693, 2.2459],
 [0.1001, 1.5991],
 [1.4283, 1.9822],
 [-1.7114, 2.7723],
 [0.2614, 3.4816]]

In [1767]:
def crossover_parent_pairing(selection_winners):
    np.random.shuffle(selection_winners)
    paired_parents = []
    for i in range(0, len(selection_winners) - len(selection_winners) % 2, 2):
        paired_parents.append([selection_winners[i], selection_winners[i + 1]])

    if len(selection_winners) % 2 != 0:
        paired_parents.append(selection_winners[-1])
    
    return paired_parents

In [1768]:
paired_parents = crossover_parent_pairing(selection_winners)
paired_parents

[[[-1.7114, 2.7723], [0.2614, 3.4816]],
 [[1.9693, 2.2459], [1.4283, 1.9822]],
 [0.1001, 1.5991]]

In [1769]:
def crossover(paired_parents):
    new_generation = []
    for parents in paired_parents:
        try:
            rand = np.random.uniform(low=0.0, high=1.0, size=None)
            new_generation.append([round((rand * parents[0][0]) + (1 - rand) * parents[1][0], 4),\
             round((1 - rand) * parents[0][1] + (rand * parents[1][1]), 4)])
            new_generation.append(parents[0])
            new_generation.append(parents[1])
        except:
            new_generation.append(parents)

    return new_generation

In [1770]:
new_generation = crossover(paired_parents)
new_generation

[[-1.5457, 3.422],
 [-1.7114, 2.7723],
 [0.2614, 3.4816],
 [1.5018, 2.2101],
 [1.9693, 2.2459],
 [1.4283, 1.9822],
 [0.1001, 1.5991]]

In [1771]:
def mutation(population, mutation_sigma, lower_bound, upper_bound, mutation_rate=0.1):
    mutation_chromosome_indices = choice(np.array(range(len(population))),\
                                         math.ceil(len(population) * mutation_rate),\
                                         replace=False)
    for i in mutation_chromosome_indices:
        for idx, gene in enumerate(population[i]):
            mutation_point = randint(0, 2)
            if mutation_point == 1:
                valid_mutation = False
                while valid_mutation == False:       
                    rand = np.random.uniform(low=0.0, high=1.0, size=None)
                    new_gene = round(gene + (mutation_sigma * rand), 4)
                    if new_gene > lower_bound and new_gene < upper_bound:
                        population[i][idx] = new_gene
                        valid_mutation = True

    return population

In [1772]:
new_generation = mutation(new_generation, 0.35, -5.12, 5.12, mutation_rate=0.1)
new_generation

[[-1.5457, 3.422],
 [-1.7114, 2.7723],
 [0.2614, 3.4816],
 [1.5018, 2.2101],
 [2.276, 2.2459],
 [1.4283, 1.9822],
 [0.1001, 1.5991]]

In [1773]:
def continuous_genetic_algorithm(init_population, min_bound, max_bound, mutation_sigma, selection_rate=0.5, mutation_rate=0.1, generations=10):
    population = init_population
    for i in range(generations):
        print(f"**********************************Generation {i + 1}**********************************")
        pop_fitness_data = rastrigin_cost_func(population)
        ranked_values = get_rank_weighting(population_cost, selection_rate)
        selection_winners = []
        for i in ranked_values:
            selection_winners.append(i[1:-2])
        paired_parents = crossover_parent_pairing(selection_winners)
        new_generation = crossover(paired_parents)
        population = mutation(new_generation, mutation_sigma, min_bound, max_bound, mutation_rate)

In [1774]:
init_population = intitialize_population(-5.19, 5.19, 2)
init_population

array([[ 2.94822239,  3.68293413],
       [-2.75724076,  5.0610298 ],
       [ 4.98711808,  1.28755038],
       [ 3.21125866,  4.88952551],
       [ 2.38780051,  0.26694122],
       [-4.70984603, -3.21334571],
       [-2.39990113,  3.63308806],
       [ 3.86077798,  0.15582027],
       [-4.52284103,  4.23782917],
       [ 1.8356002 ,  4.65707892]])

In [1775]:
continuous_genetic_algorithm(init_population, -5.19, 5.19, 0.35, generations=100)

**********************************Generation 1**********************************
*----------------------------Performance------------------------------*
    Chromosomes           Scores
[2.9482, 3.6829] ------> 36.8708
[-2.7572, 5.061] ------> 43.4879
[4.9871, 1.2876] ------> 38.8994
[3.2113, 4.8895] ------> 44.1233
[2.3878, 0.2669] ------> 34.4516
[-4.7098, -3.2133] ------> 52.7218
[-2.3999, 3.6331] ------> 53.7481
[3.8608, 0.1558] ------> 22.9399
[-4.5228, 4.2378] ------> 67.5485
[1.8356, 4.6571] ------> 45.4473
*---------------------------------------------------------------------*
**********************************Generation 2**********************************
*----------------------------Performance------------------------------*
    Chromosomes           Scores
[-1.0329, 2.0385] ------> 5.7264
[0.3393, 1.5991] ------> 36.1166
[-1.7114, 2.7723] ------> 31.6196
[1.4035, 3.0722] ------> 30.6371
[1.9693, 2.2459] ------> 18.8501
[0.2614, 3.4816] ------> 42.8388
[1.4283, 1.9822] ------